{{- include "hlib.secret" (dict "context" . "override" "cronj.secret") -}}
{{- define "cronj.secret" -}}
stringData:
  POSTGRES_USERNAME: {{ .Values.cronj.postgres.username }}
  POSTGRES_PASSWORD: {{ .Values.cronj.postgres.password }}
{{- end -}}
