{{- define "hlib.secret.tpl" -}}
{{- $ := .context -}}
{{- $secret := .values | default $.Values.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hlib.util.tplrender" (dict "value" ($secret.name | default (include "hlib.fullname" $)) "context" $) }}
  labels: {{- include "hlib.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
  {{- if $secret.annotations }}
  {{- include "hlib.util.tplrender" (dict "value" $secret.annotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
{{- if hasKey $secret "immutable" }}
immutable: {{ include "hlib.util.tplrender" (dict "value" $secret.immutable "context" $) }}
{{- end }}
{{- end }}

{{- define "hlib.secret" -}}
{{- if .override }}
{{- $_ := set . "base" "hlib.secret.tpl" -}}
{{- include "hlib.util.merge" . -}}
{{- else }}
{{- toYaml (fromYaml (include "hlib.secret.tpl" .)) -}}
{{- end -}}
{{- end -}}
