{{- define "hlib.serviceAccount.tpl" -}}
{{- $ := .context -}}
{{- $sa := .values | default $.Values.serviceAccount -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hlib.util.tplrender" (dict "value" ($sa.name | default (include "hlib.fullname" $)) "context" $) }}
  labels: {{- include "hlib.labels" $ | nindent 4 }}
  {{- if $sa.annotations }}
  annotations: {{- include "hlib.util.tplrender" (dict "value" $sa.annotations "context" $) | nindent 4 }}
  {{- end }}
{{- if hasKey $sa "automountServiceAccountToken" }}
automountServiceAccountToken: {{ include "hlib.util.tplrender" (dict "value" $sa.automountServiceAccountToken "context" $) }}
{{- end }}
{{- end }}

{{- define "hlib.serviceAccount" -}}
{{- if .override }}
{{- $_ := set . "base" "hlib.serviceAccount.tpl" -}}
{{- include "hlib.util.merge" . -}}
{{- else }}
{{- toYaml (fromYaml (include "hlib.serviceAccount.tpl" .)) -}}
{{- end -}}
{{- end -}}
