{{- include "hlib.secret" (dict "context" . "override" "envVars.secret") -}}
{{- define "envVars.secret" -}}
stringData:
  POSTGRES_USERNAME: {{ .Values.envVars.postgres.username }}
  POSTGRES_PASSWORD: {{ .Values.envVars.postgres.password }}
  JWT_SECRET: {{ .Values.envVars.jwt.secret }}
{{- end -}}
