{{- include "hlib.secret" (dict "context" . "override" "simple.secret") -}}
{{- define "simple.secret" -}}
stringData:
  POSTGRES_USERNAME: {{ .Values.simple.postgres.username }}
  POSTGRES_PASSWORD: {{ .Values.simple.postgres.password }}
{{- end -}}
