{{- include "hlib.secret" (dict "context" . "override" "multi-depl.secret") -}}
{{- define "multi-depl.secret" -}}
stringData:
  POSTGRES_USERNAME: {{ .Values.multiDepl.postgres.username }}
  POSTGRES_PASSWORD: {{ .Values.multiDepl.postgres.password }}
{{- end -}}
