{{- include "hlib.secret" (dict "context" . "override" "consumer.secret") -}}
{{- define "consumer.secret" -}}
stringData:
  POSTGRES_USERNAME: {{ .Values.app.postgres.username | default (((.Values.global).postgres).username) }}
  POSTGRES_PASSWORD: {{ .Values.app.postgres.password | default (((.Values.global).postgres).password) }}
{{- end -}}
