apiVersion: v2
appVersion: "1.29"
description: A Helm chart for deploying Simple application
keywords:
- simple
name: simple
type: application
version: "1.29"
icon: https://raw.githubusercontent.com/anatolek/hlib/master/img/icon.png
dependencies:
- name: hlib
  version: ">= 0.0.0"
  repository: https://github.com/anatolek/hlib
